[package]
name = "scraper_imdb"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking"] }
scraper = "0.20.0"
tokio = { version = "1.40.0", features = ["full"] }
urlencoding = "2.1.3"
